In [1]:
import sys
import os
import pandas as pd
from pprint import pprint
wd = %pwd
parent = os.path.dirname(wd)
fdel = os.path.sep
sys.path.append(parent+fdel+"src")
import tedata as ted

INFO - tedata package initialized successfully!

In [2]:
ted.find_active_drivers(close_all_drivers=True, close__all_scrapers=True)

{'Active webdrivers': [], 'Active TE_Scrapers': []}

In [3]:
search = ted.search_TE()

INFO - New firefox webdriver created.
INFO - Loading home page at https://tradingeconomics.com/ ...
INFO - Home page at https://tradingeconomics.com loaded successfully! Search box element found.

In [4]:
search.search_trading_economics("ism")

INFO - Clicking search box...
INFO - Entering search term: ism
INFO - Waiting for dropdown suggestions to appear...
INFO - Dropdown suggestions found.

Found search results dropdown.

In [5]:
search.result_table

,country,metric,url
result,,,
0,united states,business confidence,https://tradingeconomics.com/united-states/bus...
1,united states,non manufacturing pmi,https://tradingeconomics.com/united-states/non...
2,united states,ism manufacturing new orders,https://tradingeconomics.com/united-states/ism...
3,united states,ism manufacturing employment,https://tradingeconomics.com/united-states/ism...
4,united states,ism manufacturing prices,https://tradingeconomics.com/united-states/ism...
5,united states,ism manufacturing production,https://tradingeconomics.com/united-states/ism...
6,united states,ism non manufacturing prices,https://tradingeconomics.com/united-states/ism...

In [6]:
bilp = search.get_data(0)

INFO - scrape_chart function: Scraping chart at: https://tradingeconomics.com/united-states/business-confidence, time: 2026-04-28 11:53:20.432516, method: highcharts_api

Attempting to scrape data for result  0 ,  united states business confidence
Scraping data from: https://tradingeconomics.com/united-states/business-confidence

INFO - Page loaded successfully.
INFO - Chart types dictionary created successfully: dict_keys(['Column', 'Spline', 'Areaspline', 'Stepline', 'Line', 'Area'])
INFO - No date span selected, defaulting to: 1Y
INFO -
Series metadata:
 {'indicator': 'business confidence', 'country': 'United States', 'source': 'Trading Economics', 'id': 'united-states/business-confidence', 'frequency': 'monthly', 'symbol': 'napmpmi', 'te_type': 'te', 'units': 'points', 'original_source': 'Institute for Supply Management', 'title': 'United States ISM Manufacturing PMI'}
INFO - menu2-bottom 10Y not found, available in that zone: []
INFO - Clicked 10Y via standard #dateSpansDiv
INFO - Successfully extracted series data from Highcharts.
INFO - Successfully scraped series from Highcharts API.

Data scraped successfully from: https://tradingeconomics.com/united-states/business-confidence

In [7]:
bilp.plot_series()

In [8]:
scrapped = ted.scrape_chart(country = "united-states", indicator = "population", method = "path", start_date="2025-09-01")

WARNING: Trading Economics has disabled the custom date range setter for non-premium users. Data may be limited based on subscription level.

INFO - New firefox webdriver created.
INFO - scrape_chart function: Scraping chart at: https://tradingeconomics.com/united-states/population, time: 2026-04-28 11:53:39.704716, method: path
INFO - Page loaded successfully.
INFO - Chart types dictionary created successfully: dict_keys(['Column', 'Spline', 'Areaspline', 'Stepline', 'Line', 'Area'])
INFO - No date span selected, defaulting to: 5Y
INFO -
Series metadata:
 {'indicator': 'population', 'country': 'United States', 'source': 'Trading Economics', 'id': 'united-states/population', 'frequency': 'yearly', 'symbol': 'usa sp.pop.totl', 'te_type': 'te', 'units': 'Million', 'original_source': 'U.S. Census Bureau', 'title': 'United States Population'}
INFO - menu2-bottom 10Y not found, available in that zone: []
INFO - Clicked 10Y via standard #dateSpansDiv
INFO - Chart type set to: Spline (using JavaScript)

Using selenium and tooltip scraping to construct the date time index for the time-series, this'll take a bit...

INFO - Time taken to select chart type: 0.8378672639992146
INFO - Successfully initialized tooltip with simple mouse event

INFO - Time taken to execute JS code: 3.354562778997206

Frequency of time-series:  YS-JAN

INFO - Date span set to custom range: 1950-01-01 to 2026-04-28 (using JavaScript)
INFO - Chart type set to: Spline (using JavaScript)
INFO - Successfully initialized tooltip with simple mouse event

End date: 2025-01-01 00:00:00

INFO - Successfully initialized tooltip with simple mouse event

INFO - Start and end values scraped from tooltips:
{'start_date': Timestamp('2016-01-01 00:00:00'), 'start_value': 323.07, 'end_date': Timestamp('2025-01-01 00:00:00'), 'end_value': 342.28, 'unit_str': 'Million'}
INFO - DateTimeIndex created successfully for the time-series.
INFO - Y-axis values scraped successfully.
INFO - Series path extraction method: Extracting series data from chart soup.
INFO - Date span: MAX. Chart type: .splineChart, URL: https://tradingeconomics.com/united-states/population.
INFO - DateTimeIndex applied to series, series attribute updated.
INFO - Scale series method:
unit_per_pix calculated from the y axis ticks: 0.07767722473604827,
unit_per_pix from axis limits and self.y_axis (probably best way): 0.0777027027027027
yaxis top tick: 344.0, yaxis bot tick: 321.0
axis_limits: 335.0, 40.0, y-axis series min & max pixel values: 335.5, 39.5
INFO - Successfully scaled series.
INFO - Successfully scraped time-series from chart at:  https://tradingeconomics.com/united-states/population, now getting some metadata...

Start date: 2016-01-01 00:00:00
End date: 2025-01-01 00:00:00
y_heights:  [335.5, 284.5, 232.5, 181.5, 130.5, 78.5, 39.5]
pixheights:  [335.5, 284.5, 232.5, 181.5, 130.5, 78.5, 39.5]
Successfully scraped y-axis values from the chart:
 pixheight
335.5    321.0
284.5    325.0
232.5    329.0
181.5    333.0
130.5    337.0
78.5     341.0
39.5     344.0
Name: ytick_label, dtype: float64
Unit per pix forumlation, 344.0, 321.0, 23.0, 296.0, 40.0, 335.0, 0.0777027027027027
Series crosses zero, x-axis should be at about pixel y-cordinate:  None
Got metadata.

Series tail: 2021-01-01    333.778689
2022-01-01    335.410135
2023-01-01    338.409966
2024-01-01    340.941385
2025-01-01    342.246959
Freq: YS-JAN, Name: population, dtype: float64

Scraping complete! Happy pirating yo!

In [9]:
scrapped.series

2016-01-01    323.101858
2017-01-01    325.895357
2018-01-01    327.498953
2019-01-01    328.344088
2020-01-01    331.852196
2021-01-01    333.778689
2022-01-01    335.410135
2023-01-01    338.409966
2024-01-01    340.941385
2025-01-01    342.246959
Freq: YS-JAN, Name: population, dtype: float64

In [10]:
scrapped.plot_series()

In [11]:
pop = scrapped.series.iloc[-1] * 1000000
medicare_2024 = 1.6 * 10**12
dollars_per_person_perYear = medicare_2024/pop
dollars_per_person_perYear

np.float64(4674.986747952475)

In [12]:
scr = ted.TE_Scraper(headless = False)
scr.load_page("https://tradingeconomics.com/canada/retail-sales")

INFO - New firefox webdriver created.
INFO - Page loaded successfully.
INFO - Chart types dictionary created successfully: dict_keys(['Column', 'Spline', 'Areaspline', 'Stepline', 'Line', 'Area'])
INFO - No date span selected, defaulting to: 1Y

True

In [13]:
scr.set_date_span("10Y")

INFO - Date span set to: 10Y

True

In [14]:
scr.set_max_date_span_viaCalendar()

INFO - Date span set to custom range: 1950-01-01 to 2026-04-28 (using JavaScript)

In [15]:
scr.scrape_metadata()
scr.init_tooltipScraper()

INFO -
Series metadata:
 {'indicator': 'retail sales', 'country': 'Canada', 'source': 'Trading Economics', 'id': 'canada/retail-sales', 'frequency': 'monthly', 'symbol': 'canretailsalesmom', 'te_type': 'te', 'units': '%', 'original_source': 'Statistics Canada', 'title': 'Canada Retail Sales MoM'}
INFO - TooltipScraper object initialised successfully.

In [16]:
scr.update_chart()
scr.chart_soup.select(".highcharts-tooltip")

[]

In [17]:
scr.tooltip_scraper.initialize_tooltip_simple()

INFO - Successfully initialized tooltip with simple mouse event

True

In [18]:
scr.tooltip_scraper.first_last_dates_js()

INFO - Successfully initialized tooltip with simple mouse event

{'start_date': None, 'start_value': None, 'end_date': None, 'end_value': None}

In [19]:
scr.tooltip_scraper.latest_points_js()

INFO - Button not found or not clickable: #dateSpansDiv a:nth-child(1)
INFO - Error setting date span: 1Y, check that the date span button is clickable.
INFO - Chart type set to: Spline (using JavaScript)
INFO - Time taken to select chart type: 0.6921217810013331
INFO - Successfully initialized tooltip with simple mouse event

INFO - Time taken to execute JS code: 0.5810618909999903

[{'date': 'Mar 2026', 'value': '0.6%', 'x': 784, 'y': 424.5},
 {'date': 'Feb 2026', 'value': '0.7%', 'x': 779, 'y': 424.5},
 {'date': 'Jan 2026', 'value': '1.2%', 'x': 769, 'y': 424.5},
 {'date': 'Dec 2025', 'value': '-0.4%', 'x': 759, 'y': 424.5},
 {'date': 'Nov 2025', 'value': '1.2%', 'x': 749, 'y': 424.5},
 {'date': 'Oct 2025', 'value': '0.1%', 'x': 734, 'y': 424.5},
 {'date': 'Sep 2025', 'value': '-1%', 'x': 724, 'y': 424.5},
 {'date': 'Aug 2025', 'value': '0.9%', 'x': 714, 'y': 424.5},
 {'date': 'Jul 2025', 'value': '-0.6%', 'x': 704, 'y': 424.5},
 {'date': 'Jun 2025', 'value': '1.4%', 'x': 689, 'y': 424.5}]

In [20]:
scraped = ted.scrape_chart(country="canada", indicator="retail-sales", method = "mixed", headless=True)

INFO - New firefox webdriver created.
INFO - scrape_chart function: Scraping chart at: https://tradingeconomics.com/canada/retail-sales, time: 2026-04-28 11:54:35.841054, method: mixed
INFO - Page loaded successfully.
INFO - Chart types dictionary created successfully: dict_keys(['Column', 'Spline', 'Areaspline', 'Stepline', 'Line', 'Area'])
INFO - No date span selected, defaulting to: 1Y
INFO -
Series metadata:
 {'indicator': 'retail sales', 'country': 'Canada', 'source': 'Trading Economics', 'id': 'canada/retail-sales', 'frequency': 'monthly', 'symbol': 'canretailsalesmom', 'te_type': 'te', 'units': '%', 'original_source': 'Statistics Canada', 'title': 'Canada Retail Sales MoM'}
INFO - menu2-bottom 10Y not found, available in that zone: []
INFO - Clicked 10Y via standard #dateSpansDiv
INFO - Chart type set to: Spline (using JavaScript)

Using selenium and tooltip scraping to construct the date time index for the time-series, this'll take a bit...

INFO - Time taken to select chart type: 0.6593238620007469
INFO - Successfully initialized tooltip with simple mouse event

INFO - Time taken to execute JS code: 0.3182453150002402

Frequency of time-series:  MS

INFO - Date span set to custom range: 1950-01-01 to 2026-04-28 (using JavaScript)
INFO - Chart type set to: Spline (using JavaScript)
INFO - Successfully initialized tooltip with simple mouse event

End date: 2026-03-01 00:00:00

INFO - Successfully initialized tooltip with simple mouse event

INFO - Start and end values scraped from tooltips:
{'start_date': Timestamp('2016-04-01 00:00:00'), 'start_value': 1.0, 'end_date': Timestamp('2026-03-01 00:00:00'), 'end_value': 0.6, 'unit_str': '%'}
INFO - DateTimeIndex created successfully for the time-series.

Start date: 2016-04-01 00:00:00
End date: 2026-03-01 00:00:00

INFO - Successfully initialized tooltip with simple mouse event

INFO -  Using mixed scraping approach, slowest, highest accuracy. Splitting x_index into subIndexes        Total points: 120, Max chunk size: 500, Number of chunks: 1, remainder: 0
INFO - x_index Start date: 2016-04-01 00:00:00, End date: 2026-03-01 00:00:00
INFO - SubIndex 0: 120 points, from 2016-04-01 00:00:00 to 2026-03-01 00:00:00, frequency: MS
INFO - Date span set to custom range: 2016-04-01 to 2026-04-28 (using JavaScript)
INFO - Chart type set to: Spline (using JavaScript)
INFO - Chart type set to: Spline (using JavaScript)
INFO - Time taken to select chart type: 0.8221541029997752
INFO - Successfully initialized tooltip with simple mouse event

INFO - Time taken to execute JS code: 3.8503975729981903
INFO - Successfully scraped full series from tooltips.
INFO - Successfully scraped full series using mixed method.

In [21]:
scraped.plot_series()

In [22]:
scud = ted.scrape_chart(country="united-states", indicator="retail-sales", method = "tooltips", headless=True)

INFO - New firefox webdriver created.
INFO - scrape_chart function: Scraping chart at: https://tradingeconomics.com/united-states/retail-sales, time: 2026-04-28 11:55:05.072449, method: tooltips
INFO - Page loaded successfully.
INFO - Chart types dictionary created successfully: dict_keys(['Column', 'Spline', 'Areaspline', 'Stepline', 'Line', 'Area'])
INFO - No date span selected, defaulting to: 1Y
INFO -
Series metadata:
 {'indicator': 'retail sales', 'country': 'United States', 'source': 'Trading Economics', 'id': 'united-states/retail-sales', 'frequency': 'monthly', 'symbol': 'rstamom', 'te_type': 'te', 'units': '%', 'original_source': 'U.S. Census Bureau', 'title': 'US Retail Sales'}
INFO - TooltipScraper object initialised successfully.
INFO - menu2-bottom 10Y not found, available in that zone: []
INFO - Clicked 10Y via standard #dateSpansDiv
INFO - Successfully initialized tooltip with simple mouse event

INFO - Chart type set to: Spline (using JavaScript)
INFO - Chart type set to: Spline (using JavaScript)
INFO - Time taken to select chart type: 0.6943289720002213
INFO - Successfully initialized tooltip with simple mouse event

INFO - Time taken to execute JS code: 4.5033280509996985
INFO - Successfully scraped full series from tooltips.
INFO - Successfully scraped full series from tooltips.

In [23]:
scud.plot_series()

## Test chrome browser support & commodity series extraction

In [24]:
oil = ted.scrape_chart(url = "https://tradingeconomics.com/commodity/brent-crude-oil")
oil.plot_series()

INFO - New firefox webdriver created.
INFO - scrape_chart function: Scraping chart at: https://tradingeconomics.com/commodity/brent-crude-oil, time: 2026-04-28 11:57:46.531822, method: highcharts_api
INFO - Page loaded successfully.
INFO - Chart type buttons not available on this chart type (may be a commodity/high-frequency chart).
INFO -
Series metadata:
 {'indicator': 'brent crude oil', 'country': 'Commodity', 'source': 'Trading Economics', 'id': 'commodity/brent-crude-oil', 'frequency': 'intraday', 'symbol': 'CO1', 'te_type': 'te', 'units': 'USD/Bbl', 'original_source': 'unknown', 'title': 'Brent crude oil - Price - Chart - Historical Data - News'}
INFO - Clicked 10Y via menu2-bottom commodity selector
INFO - Successfully extracted series data from Highcharts.
INFO - Successfully scraped series from Highcharts API.

In [25]:
gold = ted.scrape_chart(url = "https://tradingeconomics.com/commodity/gold", browser="chrome")
gold.plot_series()

INFO - New chrome webdriver created.
INFO - scrape_chart function: Scraping chart at: https://tradingeconomics.com/commodity/gold, time: 2026-04-28 12:03:20.218686, method: highcharts_api
INFO - Page loaded successfully.
INFO - Chart type buttons not available on this chart type (may be a commodity/high-frequency chart).
INFO -
Series metadata:
 {'indicator': 'gold', 'country': 'Commodity', 'source': 'Trading Economics', 'id': 'commodity/gold', 'frequency': 'intraday', 'symbol': 'XAUUSD', 'te_type': 'te', 'units': 'USD/t.oz', 'original_source': 'unknown', 'title': 'Gold - Price - Chart - Historical Data - News'}
INFO - Clicked 10Y via menu2-bottom commodity selector
INFO - Successfully extracted series data from Highcharts.
INFO - Successfully scraped series from Highcharts API.

In [26]:
chrome_search = ted.search_TE(browser="chrome")
chrome_search.search_trading_economics("wheat")
chrome_search.result_table

INFO - New chrome webdriver created.
INFO - Loading home page at https://tradingeconomics.com/ ...
INFO - Home page at https://tradingeconomics.com loaded successfully! Search box element found.
INFO - Clicking search box...
INFO - Entering search term: wheat
INFO - Waiting for dropdown suggestions to appear...
INFO - Dropdown suggestions found.

Found search results dropdown.

,country,metric,url
result,,,
0,commodity,wheat,https://tradingeconomics.com/commodity/wheat
1,united states,prospective plantings wheat,https://tradingeconomics.com/united-states/pro...
2,united states,grain stocks wheat,https://tradingeconomics.com/united-states/gra...
3,exports,products milling industry malt starches inulin...,https://tradingeconomics.com/united-states/exp...
4,imports,products milling industry malt starches inulin...,https://tradingeconomics.com/united-states/imp...
5,imports,products milling industry malt starches inulin...,https://tradingeconomics.com/china/imports/pro...
6,exports,products milling industry malt starches inulin...,https://tradingeconomics.com/china/exports/pro...

In [27]:
chrome_search.get_data(0).plot_series()

Attempting to scrape data for result  0 ,  commodity wheat
Scraping data from: https://tradingeconomics.com/commodity/wheat

INFO - scrape_chart function: Scraping chart at: https://tradingeconomics.com/commodity/wheat, time: 2026-04-28 12:05:39.764489, method: highcharts_api
INFO - Page loaded successfully.
INFO - Chart type buttons not available on this chart type (may be a commodity/high-frequency chart).
INFO -
Series metadata:
 {'indicator': 'wheat', 'country': 'Commodity', 'source': 'Trading Economics', 'id': 'commodity/wheat', 'frequency': 'intraday', 'symbol': 'W 1', 'te_type': 'te', 'units': 'USd/Bu', 'original_source': 'unknown', 'title': 'Wheat - Price - Chart - Historical Data - News'}
INFO - Clicked 10Y via menu2-bottom commodity selector
INFO - Successfully extracted series data from Highcharts.
INFO - Successfully scraped series from Highcharts API.

Data scraped successfully from: https://tradingeconomics.com/commodity/wheat